name: .Publish

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 7.0.x

      - name: Restore dependencies
        run: dotnet restore Feedboard.slnf

      - name: Build
        run: dotnet build Feedboard.slnf --no-restore

      - name: Test
        run: dotnet test Feedboard.slnf --no-build --verbosity normal

  build-api-image-and-push-image:
    needs: build
    if: success()
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Docker login
        run: docker login --username ${{ secrets.GH_LOGIN }} --password ${{ secrets.DOCKER_TOKEN }} ghcr.io

      - name: Build image
        run: docker build . --tag ghcr.io/feedboards/feedboard-api:latest -f ./Infrastructure/API/Dockerfile

      - name: push
        run: docker push ghcr.io/feedboards/feedboard-api:latest

  build-mssql-image-and-push-image:
    needs: build
    if: success()
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Docker login
        run: docker login --username ${{ secrets.GH_LOGIN }} --password ${{ secrets.DOCKER_TOKEN }} ghcr.io

      - name: Build image
        run: docker build . --tag ghcr.io/feedboards/feedboard-databse-mssql:latest -f ./Infrastructure/Database/Dockerfile

      - name: push
        run: docker push ghcr.io/feedboards/feedboard-databse-mssql:latest
